### ISSUE TITLE
updatingdata.py should be able to update CSV files as well as JSON

### ISSUE THREAD

**Issue by 2ale2** [2ale2/scambifestival-ubjs#1]
The script should be able to update CSV files as well. Even if the change is relatively simple, there is a thing to think about: **since the text parsed has fields containing commas, using commas as CSV separators could cause issues** with text parsing (for example with 'description' fields about *labs* and *pinolos*). So FYI **the separator will be the pipe** ("|") which is another separator commonly used for CSV. Hope this will work.

**Comment by xplosionmind** [comment]
@2ale2 the common practice (used already in all the CSVs that scambi.org had) is to normally use commas inside CSV fields by simply enclosing the in double quotes (`"`). It is possible to enclose text within double quotes even if there are no commas inside, or quote every field. It is the same.

e.g.:
```
what,why,where,when
Cosa,boh,Sanremo,"Domani, forse"
"Thing","boooh","tomorrow"
```

Anyway, changing the separator would require some meddling with Eleventy’s configuration, but more importantly it uses a non-standard separator… it could be doable but it is not desirable. If it is impossible to use the double quotes solution, I will try to work this problem out within Eleventy.

**Comment by 2ale2** [comment]
@xplosionmind I'll try to use commas and quotes.

In order to make it work, we must be sure that no fields contain more quotes inside.

**Comment by xplosionmind** [comment]
> we must be sure that no fields contain more quotes inside.

1. In 99% of the cases curly quotes (`“`,`”`) should be used, so no problem
1. In that 1% of the cases, quotes can be escaped with no problem `\"`

All of this stuff is usually handled automatically by any CSV parser, it surprises me that this is not the case…

**Comment by 2ale2** [comment]
Usually a Python CSV parser (like the one from Pandas or the built-in 'csv'  parser) creates a CSV file in a specified local directory: it's useless and a waste of resources in our case, since the GitHub API requires an output file name and the content that will be written in it.

The script works formatting a string in JSON or CSV depending on the selected output format using built-in functions if  possible.

In particular, CSV text content is created using  nested cycles, so escaping a quote requires a suitable algorithm.

I'll work on it. Not a problem at all.

Issue will be closed.
